#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

require __DIR__.'/src/bootstrap.php';

$console = require __DIR__.'/src/console.php';
$console->run();