<?php
$app['races'] = array(
    'vg2012' => array(
        'id'     => 'vg2012',
        'departure'     => "Les Sables-d'Olonne",
        'departure_lat' => '46.4972',
        'departure_lon' => '-1.7833',
        'arrival'       => "Les Sables-d'Olonne",
        'arrival_lat'   => '46.4972',
        'arrival_lon'   => '-1.7833',
        'start_date'    => 'saturday 10 november 2012 15:02',
        'parser'        => 'vg',
        'type'          => 'race',
    ),
    'guochuansailing-2012' => array(
        'id'     => 'guochuansailing-2012',
        'departure'     => 'Sanghai',
        'departure_lat' => '46',
        'departure_lon' => '-1',
        'arrival'       => 'Sanghai',
        'arrival_lat'   => '47',
        'arrival_lon'   => '-1',
        'start_date'    => 'saturday 10 november 2012 15:02',
        'url_update'    => 'http://guochuansailing.geovoile.com/roundtheworld/2012/shared/data/race/update.hwz',
        'url_update'    => 'http://guochuansailing.geovoile.com/roundtheworld/2012/shared/data/race/update.hwz',
        'url_static'    => 'http://guochuansailing.geovoile.com/roundtheworld/2012/shared/data/race/static.hwz',
        'parser'        => 'geovoile',
        'type'          => 'record',
    ),
    'soldini-2012' => array(
        'id'     => 'soldini-2012',
        'departure'     => 'New York',
        'departure_lat' => '46',
        'departure_lon' => '-1',
        'arrival'       => 'San Francisco',
        'arrival_lat'   => '47',
        'arrival_lon'   => '-1',
        'start_date'    => 'saturday 10 november 2012 15:02',
        'url_update'    => 'http://soldini.geovoile.com/newyorksanfrancisco/2012/private/data/update.hwz',
        'url_static'    => 'http://soldini.geovoile.com/newyorksanfrancisco/2012/private/data/static.hwz',
        'parser'        => 'geovoile',
        'type'          => 'record',
    ),
    'tbm2013' => array(
        'id'     => 'tbm2013',
        'departure'     => 'Brest',
        'departure_lat' => '48.390604',
        'departure_lon' => '-4.486901',
        'arrival'       => 'Fort-de-France',
        'arrival_lat'   => '14.603518',
        'arrival_lon'   => '-61.066818',
        'start_date'    => 'sunday 17 march 2013 13:00',
        'url_update'    => 'http://transat-bretagnemartinique.geovoile.com/2013/shared/data/race/leg1.update.hwz',
        'url_static'    => 'http://transat-bretagnemartinique.geovoile.com/2013/shared/data/race/leg1.static.hwz?v=43414423',
        'parser'        => 'geovoile',
        'type'          => 'race',
    ),
);
